export ARCH=arm64
export SUBARCH=arm32
make O=out clean
make O=out mrproper
make O=out davinci_defconfig
export KBUILD_COMPILER_STRING="$(/home/kazuki/proton-clang/bin/clang --version | head -n 1 | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')";
export USE_CCACHE=1
export PATH="/home/kazuki/proton-clang/bin:$PATH"
PATH="/home/kazuki/proton-clang/bin:$PATH"
make O=out -j$(nproc --all) \
	CC="clang" \
	CLANG_TRIPLE="aarch64-linux-gnu-" \
	CROSS_COMPILE="aarch64-linux-gnu-" \
	CROSS_COMPILE_ARM32="arm-linux-gnueabi-" \
	LD=ld.lld \
	AR=llvm-ar \
	NM=llvm-nm \
	OBJCOPY=llvm-objcopy \
	OBJDUMP=llvm-objdump \
	STRIP=llvm-strip
